### ISSUE TITLE
Boot/reboot/shutdown splash screen

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-raspberrypi#1]
# Steps to reproduce issue 
Connect to the HDMI connected to a monitor
Boot the device

# Expected result 
Resin logo splash screen should be visible

# Actual result 
RaspberryPi: No splash screen at boot

# Other information 
Reported by: Andrei Gherzan 

Test configuration: RaspberryPi 

Test case number: TC07 

Test run: [https://resinio.testlodge.com/projects/16238/runs/192879?tab=2&run_section_id=168778&executed_case_id=9333888#executed_case_9333888](https://resinio.testlodge.com/projects/16238/runs/192879?tab=2&run_section_id=168778&executed_case_id=9333888#executed_case_9333888)

**Comment by telphan** [comment]
Is this issue present on Raspberrypi or Raspberrypi2?

**Comment by agherzan** [comment]
Rpi1

**Comment by telphan** [comment]
Well, this is not exactly a bug. The reason for the splash not showing on rpi1 is slow hardware. It takes too long to show the splash. Therefore the boot finishes before plymouth has a chance of showing splash.

**Comment by agherzan** [comment]
Yes. We are aware of this but maybe we could optimize boot to inject the splash service sooner in the boot seq services?

**Comment by telphan** [comment]
There is only one way that springs to mind, but that involves making use of an initramfs.

**Comment by lurch** [comment]
The [new version of Raspbian](https://www.raspberrypi.org/blog/introducing-pixel/) includes a splashscreen, maybe there's code you can borrow from there?

**Comment by agherzan** [comment]
Sounds interesting. We will take a look on this.

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#71
