### ISSUE TITLE
Update kernel to 4.9.29+

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-raspberrypi#120]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_29fx)

**Comment by floion** [comment]
I think this should be done from the bsp instead of doing it here

**Comment by agherzan** [comment]
I agree.

**Comment by willnewton** [comment]
It looks like Pyro uses 4.9 by default.

**Comment by agherzan** [comment]
@willnewton the request is actually for 4.9.29+.

**Comment by agherzan** [comment]
`meta-raspberrypi` pyro comes with 4.9.41 which is the latest version currently available. @willnewton can you link this to the pyro update task so we can close it as soon as that is done?

**Comment by willnewton** [comment]
This should be fixed when #126 is closed

**Comment by willnewton** [comment]
The Pyro PR has been merged so this is completed.

**Comment by qerub** [comment]
About when can one expect a Resin OS release with this kernel?

**Comment by qerub** [comment]
"@qerub unassigned @willnewton 37 seconds ago"

Uhm… Did I do something stupid or just trigger a GitHub bug?

**Comment by floion** [comment]
No idea what happened with github above.
Anyway, there should be a release for rpi3 in the following days. Stay tuned
