### ISSUE TITLE
Update latest WiFi firmware

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-raspberrypi#121]
Due to https://github.com/resin-os/meta-resin/issues/812 we want to update the wifi firmware to the one provided by Raspbian - as the issue above can't be reproduced with that version.

**Comment by floion** [comment]
I think this should be done from the bsp instead of doing it here

**Comment by agherzan** [comment]
I agree.

**Comment by willnewton** [comment]
This should be fixed when #126 is closed

**Comment by agherzan** [comment]
@shaunmulligan What firmware are we talking about here?

**Comment by shaunmulligan** [comment]
@agherzan the WiFi firmware

**Comment by agherzan** [comment]
Fixed by https://github.com/agherzan/meta-raspberrypi/pull/123

**Comment by agherzan** [comment]
Thanks @shaunmulligan clarified it in the summary and subject.

**Comment by agherzan** [comment]
@willnewton it depends if we decide to include this update in pyro only. So let's see what @shaunmulligan wants. I asked in FD.

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-raspberrypi/pull/136
