### ISSUE TITLE
Enable PCA955x IO expander in kernel config

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-raspberrypi#132]
Amber has a [PCA955](https://www.digikey.com/product-detail/en/nxp-usa-inc/PCA9554BS3118/568-9940-1-ND/3721120) IO expander module. This IC has support in linux kernel, so I think we just need to enable: `GPIO_PCA953X` and `GPIO_PCA953X_IRQ`

```
config GPIO_PCA953X
	tristate "PCA953x, PCA955x, TCA64xx, and MAX7310 I/O ports"
	depends on I2C
	help
	  Say yes here to provide access to several register-oriented
	  SMBus I/O expanders, made mostly by NXP or TI.  Compatible
	  models include:

	  4 bits:	pca9536, pca9537

	  8 bits:	max7310, pca9534, pca9538, pca9554, pca9557,
	  		tca6408

	  16 bits:	pca9535, pca9539, pca9555, tca6416

config GPIO_PCA953X_IRQ
	bool "Interrupt controller support for PCA953x"
	depends on GPIO_PCA953X=y
	help
	  Say yes here to enable the pca953x to be used as an interrupt
	  controller. It requires the driver to be built in the kernel.
```

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-raspberrypi/pull/136

**Comment by floion** [comment]
Reopening as the PR supposed to fix this had some typos.
Should be now fixed by https://github.com/resin-os/resin-raspberrypi/pull/137

**Comment by floion** [comment]
Closing this item as https://github.com/resin-os/resin-raspberrypi/pull/137 was merged
