### ISSUE TITLE
Quectel QMI based modems don't work on resinOS 2.7.5 and Greater.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-raspberrypi#147]
On raspberry pi the Quectel EC20 modem was working fine on v2.3.0, but it seems the upgrade to the 4.9 kernel of raspberry pi may have caused them to stop working. I believe its related to some patches that were added to 4.9 as referenced here: https://lists.freedesktop.org/archives/libqmi-devel/2017-February/002067.html and here: http://www.spinics.net/lists/linux-usb/msg156311.html

**Comment by shaunmulligan** [comment]
This has been fixed in resinOS v2.8.1 (thanks @agherzan and @floion )

**Comment by floion** [comment]
For reference: https://github.com/resin-os/meta-resin/pull/898
