### ISSUE TITLE
Huawei MS2131i modem occasionally causes kernel 4.9.50 to panic

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-raspberrypi#151]
It seems that occasionally when a container is started and the container udev triggers a udev replug, that the kernel will panic with this modem attached. This affects resinOS v2.7.5 on the raspberry pi family.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5a4x)

**Comment by floion** [comment]
@shaunmulligan can you recheck this now that we have upgraded the kernel?

**Comment by shaunmulligan** [comment]
@floion tested on the latest staging 2.9.3+rev1 rpi3 and wasn't able to break it, so it looks good to me

**Comment by agherzan** [comment]
Thanks @shaunmulligan . Closing the issue.
