### ISSUE TITLE
enable_uart=1 does not make bt work when using ttyS0

### ISSUE THREAD

**Issue by floion** [resin-os/resin-raspberrypi#157]
Switch bt to use ttyS0 (by using "dtoverlay=pi3-miniuart-bt" in config txt) and then also use "enable_uart=1"  in config.txt and bt will not work. If instead one uses "force_turbo=1" or "core_g=freq=250" in config.txt then bt works on ttyS0.

Needs investigation on why "enable_uart=1" it not enough to make bt work (https://www.raspberrypi.org/documentation/configuration/uart.md)

**Comment by agherzan** [comment]
This is expected. See: https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=138223&start=75#p1041713 .

**Comment by floion** [comment]
So closing this item as per my initial conclusions before opening this issue.

**Comment by agherzan** [comment]
At that point we didn't have the explaination. And there is still a question about the baudrate.
