### ISSUE TITLE
Unifying all devices onto using resin-rootA/rootB for root partition

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-raspberrypi#168]
_From @imrehg on December 1, 2017 22:54_

Not all the boards use labels when selecting the root partition. For example raspberrypi uses root=mmcblk0pX .

_Copied from original issue: resin-os/meta-resin#918_

**Comment by agherzan** [comment]
@imrehg  meta-resin provides support for LABEL based root kernel arguments. See: https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/recipes-core/initrdscripts/files/rootfs#L34 . It means that this issue needs to be moved to the raspberrypi repository as changes to cmdline.txt are needed. Could you please create an issue in resin-raspberrypi and close this one?

**Comment by floion** [comment]
Assigned Theodor as per a discussion on 6th of March here: https://github.com/resin-os/resin-raspberrypi/pull/173

**Comment by floion** [comment]
@telphan , I have recreated to PR here: https://github.com/resin-os/resin-raspberrypi/pull/189
Please review and test it on the board

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-raspberrypi/pull/189
