### ISSUE TITLE
Unable to connect to resin VPN with U-Blox modem in RNDIS mode

### ISSUE THREAD

**Issue by spanceac** [resin-os/resin-raspberrypi#187]
The board is unable to connect to resin VPN when using an U-blox Toby-L210 modem in RNDIS mode.

The error reported by the openvpn is the following: https://openvpn.net/index.php/open-source/faq/79-client/253-tls-error-tls-key-negotiation-failed-to-occur-within-60-seconds-check-your-network-connectivity.html

If the modem is switched to ECM mode, the VPN connection works OK.

This bug is present on ResinOS v2.9.6, but not on v2.3.0.

Related Front link: https://app.frontapp.com/open/cnv_gswxkp

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_aju3)

**Comment by zvin** [comment]
@spanceac @imrehg should we close this now that 2.12.5+rev2 is released?

**Comment by floion** [comment]
Yes, let's close this
