### ISSUE TITLE
Support balena fin (CM3)

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-raspberrypi#193]
The new device type will have the slug `fincm3` and will specify a `subtype_of` being `raspberrypi3`.

This was discussed in the architecture call (2018-05-01). See: https://docs.google.com/document/d/1TiA3kt7zU8ce9mlNl5EWymfQ41VWW_xPZGHSMgDORPw/edit

**Comment by floion** [comment]
When was this discussed? @shaunmulligan I thought there would not be a new device type for the fin (as per a discussion only a few days ago)

**Comment by shaunmulligan** [comment]
@floion yeah it was discussed in arch call, we are gonna make a new device type that is a subtype of the rpi

**Comment by floion** [comment]
Then I guess we can do this for other Balena Fin like boards? Or this is just a one-timer?

**Comment by agherzan** [comment]
Implemented in https://github.com/resin-os/resin-raspberrypi/pull/195
