### ISSUE TITLE
Remove `subtype_of` as we don't use it anymore

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-raspberrypi#197]
We decided to stop using `subtype_of` and allow each application add any device type of the same architecture as the main device type the application was created with.

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-raspberrypi/pull/201

**Comment by floion** [comment]
This has been fixed by https://github.com/resin-os/resin-raspberrypi/pull/202
