### ISSUE TITLE
Duplicate instructions in dashboard for fincm3

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-raspberrypi#198]
The fincm3 device type defines the provisioning instructions https://github.com/resin-os/resin-raspberrypi/blob/master/fincm3.coffee#L25. This ends up in the UI with a duplicated last step:

```
Your device should appear here in about 10 minutes. Have fun!
Your device should appear in your application dashboard within a few minutes. Have fun!
```

We should remove one of them.

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-raspberrypi/pull/199

**Comment by floion** [comment]
Closing as the fixing PR has been merged
