### ISSUE TITLE
Kernel boot messages on HDMI

### ISSUE THREAD

**Issue by telphan** [resin-os/resin-raspberrypi#30]
This is caused by the set of console=tty1 in the kernel cmdline.
NOTE: If no console is provided to the kernel then it will default to tty0 which will link to the first display (i.e. serial port)

**Comment by curcuz** [comment]
This happens also on DSI screens like tthe official raspberrypi touchscreen

**Comment by agherzan** [comment]
Indeed. It happens on anything that is hooked to tty1.

**Comment by telphan** [comment]
#36

**Comment by agherzan** [comment]
Reverted #36 (rebased) as this fix breaks serial console usability.
