### ISSUE TITLE
Pi Zero OTG support

### ISSUE THREAD

**Issue by konradko** [resin-os/resin-raspberrypi#44]
Pi Zero can be powered and accessed from single USB port (it appears as Ethernet device). That functionality is currently missing in ResinOS, as the necessary modules / kernel version are missing (they are included in 2016-05-10 release of Raspbian).

Full info: http://blog.gbaman.info/?p=791

Short guide:
https://gist.github.com/gbaman/975e2db164b3ca2b51ae11e45e8fd40a

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#76
