### ISSUE TITLE
Update firmware to fix incorrect picamera v2 flip

### ISSUE THREAD

**Issue by imrehg** [resin-os/resin-raspberrypi#48]
There was an issue discovered in the picamera firmware for the v2 camera, that the image is flipped horizontally, compared to the v1 camera by default. The fix has been applied in https://github.com/raspberrypi/firmware/commit/20958cdfe145aacdc64bded239c9d7bfe1b20bb2 and we should pull at least that version for our compilation as well.

For reference, the first meta-raspberrypi that has those changes as well is [5d79d24](http://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/commit/recipes-bsp/common/firmware.inc?id=5d79d24d36dfe87309a15581d3350afc4c47a0e3).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_nrf)

**Comment by a-musing-moose** [comment]
Thanks @imrehg

**Comment by agherzan** [comment]
This issue was moved to resin-os/resinos#77
