### ISSUE TITLE
Systemd warnings on serial-getty@ttyAMA0.service

### ISSUE THREAD

**Issue by agherzan** [resin-os/resin-raspberrypi#8]
On RPI2 - and most probably on all our devices - systemd at boot reports:

`[    5.339571] systemd[1]: serial-getty@ttyAMA0.service: Cannot add dependency job, ignoring: Unit serial-getty@ttyAMA0.service failed to load: No such file or directory.
`

**Comment by telphan** [comment]
Issue moved to [resin-os/meta-resin #120](https://github.com/resin-os/meta-resin/issues/120) via [**ZenHub.io**](https://www.zenhub.io/)
